const booksData = [
  { title: "The First Bakla", author: "Mark Dimaisip", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "Heat Index", author: "Genevieve L. Asenjo", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Altar ng Pangungulila", author: "Edbert Darwin Casten", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Lamanglupa Unlimited", author: "Edelio De los Santos", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Other Side", author: "Gerome Dela Peña", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Kapag Sinabi ko", author: "Redwin Dob", volume: "Vol. 1", stock: 0, price: 450 },
  {
    title: "Lahat Silang Hindi Nahahagip ng Paningin",
    author: "Klara Espedido",
    volume: "Vol. 1",
    stock: 0,
    price: 450,
  },
  { title: "Dilat sa Pusikit", author: "Harold Fiesta", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Wala na ang Diyos sa Simbahan", author: "Steven Lombos", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Saglit Lang", author: "Ronel Osias", volume: "Vol. 1", stock: 0, price: 450 },
  {
    title: "ang mga bata, naging binhi ng oliba, nakatanim sa lupa",
    author: "MJ Rafal",
    volume: "Vol. 1",
    stock: 0,
    price: 450,
  },
  { title: "Sa Kalsadang Puno ng Pananagimsim", author: "Renz Rosario", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Kartilya ng Katarata", author: "Brixter Tino", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Handurawan", author: "Pia Montalban", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Pumpon ng Paglilimi", author: "Christian Raynera", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Sandaang Mata sa Batok", author: "Franchezka Rosales", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "PaRaLaYa", author: "Jayson Visperas Fajardo", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "When All I Could Do Was Write", author: "Jazminne Peña", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Poetry is a Mistake", author: "Jass Sacdalan", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Metro Meka Mega", author: "Layon", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Mukha ng Pag-uwi", author: "Ivan Jetrho Mella", volume: "Vol. 1", stock: 0, price: 450 },
  { title: "Mga Larong Hindi Pambata", author: "Billy Ibarra", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Tondo Mula sa Sulok-Sulok", author: "Jayson Vega", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Dala-Dala", author: "C.L. Balagoza", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Satori sa Torres St.", author: "Ronald Araña Atilano", volume: "Vol. 2", stock: 0, price: 450 },
  {
    title: "Kung Paano Tinalo ni Mang Turing ang AI",
    author: "Lance Romulus Dayrit",
    volume: "Vol. 2",
    stock: 0,
    price: 450,
  },
  {
    title: "Ayon sa Kasabihan at iba pang Tula",
    author: "Andre Ramirez Gutierrez",
    volume: "Vol. 2",
    stock: 0,
    price: 450,
  },
  { title: "Ocean Punctuations", author: "Benj Gabun Sumbat", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "sa lungsod ng alaala", author: "Richell Isaiah S. Flores", volume: "Vol. 2", stock: 0, price: 450 },
  {
    title: "Nagluto, Naghain, Kumain at Di Nagtiira",
    author: "Aldrin Pentero",
    volume: "Vol. 2",
    stock: 0,
    price: 450,
  },
  { title: "sa mata ng bata", author: "Jasper Lomtong", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Makina", author: "Darwin Medallada", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Kara o Krus", author: "Rommel Asuncion Pamaos", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Alay Lakad", author: "Glenn Galon", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Ang Alaala ng Kaibigan", author: "Justine Taño", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Salamisim: Unang Kabanata", author: "Yanin Kwerl Pimentel", volume: "Vol. 2", stock: 0, price: 450 },
  {
    title: "Sa Malamlam na Gabi, Kumakaway ang mga Pala…",
    author: "Romel G. Samson",
    volume: "Vol. 2",
    stock: 0,
    price: 450,
  },
  { title: "Idiyay Ili: Sa Tahanang Hindi Akin", author: "Jovener S. Soro", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Sa Pagitan ng Pagmaha", author: "Angelica B. Malillin", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Kadi at iba pang Tula", author: "Heather Ann F. Pulido", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Sa Kaninong Mata", author: "Ansherina May D. Jazul", volume: "Vol. 2", stock: 0, price: 450 },
  { title: "Jusqu'à la Mort, on Fait de L'art", author: "42", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "The Gaze", author: "Ria Rebolledo", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Isang Nanay at Ilang Pagninilay", author: "Ninia dela Cruz", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "M: Mga Liham ng Ligalig at Lakbay", author: "Maria Ella Betos", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Ningas", author: "Elyrah Salanga-Torralba", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Maria", author: "Mary France Buban", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Ang Pangarap Kong Suso", author: "Wyn Gallo", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Walang Kasarian si Bernardo Carpio", author: "Klara Espedido", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Kaming Mga Nasa Bingit", author: "Carisa Mae Sanchez", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Walang Sinabi", author: "April Rose Domasig", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "The Cuil Theory, Explained", author: "Risha Mae Ordas", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Hide in the Misery", author: "Mariella Angela Olden", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "The Writer's Dilemma", author: "Trixia Marie Policarpio", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Ako ay Narito, at Narito pa rin", author: "Jil Danielle Caro", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Biyaheng Light-years Away", author: "Abi Dango", volume: "Vol. 3", stock: 0, price: 450 },
  {
    title: "Dear Ulap, at iba pang Tulang Ayaw Dinggin ng Langit",
    author: "Kimberly Rose Pillo",
    volume: "Vol. 3",
    stock: 0,
    price: 450,
  },
  { title: "Hindi Palamuti", author: "Hannah Pauline Pabilonia", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Tipak, Tibak na Danas", author: "Malaya Nicolas", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Pangkaraniwan", author: "Eluna Cepeda", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Irrational and other Math Poems", author: "Keira Viresse", volume: "Vol. 3", stock: 0, price: 450 },
  { title: "Artificial Incompetence", author: "Pura Luka Vega", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "La Reyna", author: "DJ Ellamil", volume: "Vol. 4", stock: 0, price: 450 },
  {
    title: "Ang Sweatshop, Ang Aparador, at Ang Pinakamatigas na Tsinelas sa Balat ng Lupa",
    author: "Jasper Villasis",
    volume: "Vol. 4",
    stock: 0,
    price: 450,
  },
  {
    title: "Ang Diyos Ko ay Umatened sa Pride March",
    author: "Christian Raynera",
    volume: "Vol. 4",
    stock: 0,
    price: 450,
  },
  {
    title: "Pagsasanib sa Siyudad ng Pag-ibig",
    author: "Leonard Francis Alcoran",
    volume: "Vol. 4",
    stock: 0,
    price: 450,
  },
  { title: "Emergency", author: "S. Magsayao", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "Ari at Sarili", author: "Andyleen Feje", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "Talaaarawan ni Syd Borromero", author: "C.L. Balagoza", volume: "Vol. 4", stock: 0, price: 450 },
  {
    title: "Perverse is the Society in Which the Sad Gay Lives",
    author: "Gio Potes",
    volume: "Vol. 4",
    stock: 0,
    price: 450,
  },
  { title: "Elibarra Patungong El Nolibusterismo", author: "Ezjae Zemana", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "Thirst and other Poems", author: "Arkin Frany", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "Mga Yapak at Yakap", author: "Marvin Davila Aquino", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "Aparisyon", author: "Renzo Prino", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "A Heritage of Gayness", author: "Mark Vincent dela Cruz", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "Dipositaryo ng Mga Alaala", author: "Kweyn Tagaduar", volume: "Vol. 4", stock: 0, price: 450 },
  { title: "Bakante", author: "Jobert Pillas", volume: "Vol. 4", stock: 0, price: 450 },
]

// Sales data from MULIAS report
const salesData = {
  totalBooks: 200,
  totalDisbursed: 180,
  totalLeft: 20,
  totalSales: 76600,
  totalExpenses: 77000,
  grossSales: 76600,
  vat: 6128,
  netProfit: -6528,
  bookSalesProduction: 53620,
  bookSalesOperationalExpense: 7660,
  bookSalesAuthorRoyalty: 7660,
  bookSalesSierbostenProfit: 7660,
}

// Cash flow data from BBZ report
const cashFlowData = {
  totalFunds: 3591.7,
  remainingCopies: 2095,
}

console.log("Books data:", booksData.length, "books loaded")
console.log("Sales data:", salesData)
console.log("Cash flow data:", cashFlowData)
